-- Peuple `sous_prefectures` avec les 252 enregistrements du jeu de données
-- officiel du Ministère de l'Intérieur et de l'Intégration Nationale
-- (« Liste des circonscriptions administratives et des communes de la
-- Côte d'Ivoire », data.gouv.ci, dataset "liste-des-circonscriptions-
-- administratives-et-des-communes"). Récupéré via l'API data-fair du
-- portail le 24/07 (243 sous-préfectures distinctes ; Abidjan seule
-- regroupe 10 lignes, une par commune ; 54 sous-préfectures n'ont pas de
-- commune de plein exercice — `commune` reste alors NULL).
--
-- Casse normalisée en Title Case (la source mélangeait MAJUSCULES et
-- Title Case selon les lignes) ; accents conservés/absents tels que fournis
-- par la source colonne par colonne (ex. `nom`="Zuenoula" sans accent mais
-- `commune`="Zuénoula" avec accent — les deux colonnes proviennent du même
-- fichier ministériel, pas d'une correction de notre part).

insert into public.sous_prefectures (nom, departement, region, chef_lieu_departement, commune) values
  ('Abengourou', 'Abengourou', 'Moyen Comoe', 'Abengourou', 'Abengourou'),
  ('Abidjan', 'Abidjan', 'Lagunes', 'Abidjan', 'Abobo'),
  ('Abidjan', 'Abidjan', 'Lagunes', 'Abidjan', 'Adjamé'),
  ('Abidjan', 'Abidjan', 'Lagunes', 'Abidjan', 'Attecoubé'),
  ('Abidjan', 'Abidjan', 'Lagunes', 'Abidjan', 'Cocody'),
  ('Abidjan', 'Abidjan', 'Lagunes', 'Abidjan', 'Koumassi'),
  ('Abidjan', 'Abidjan', 'Lagunes', 'Abidjan', 'Marcory'),
  ('Abidjan', 'Abidjan', 'Lagunes', 'Abidjan', 'Plateau'),
  ('Abidjan', 'Abidjan', 'Lagunes', 'Abidjan', 'Port-Bouët'),
  ('Abidjan', 'Abidjan', 'Lagunes', 'Abidjan', 'Treichville'),
  ('Abidjan', 'Abidjan', 'Lagunes', 'Abidjan', 'Yopougon'),
  ('Aboisso', 'Aboisso', 'Sud-Comoe', 'Aboisso', 'Aboisso'),
  ('Adiake', 'Adiake', 'Sud-Comoe', 'Aboisso', 'Adiaké'),
  ('Adzope', 'Adzope', 'Agneby', 'Agboville', 'Adzopé'),
  ('Affery', 'Adzope', 'Agneby', 'Agboville', 'Afféry'),
  ('Agboville', 'Agboville', 'Agneby', 'Agboville', 'Agboville'),
  ('Agnibilekrou', 'Agnibilekrou', 'Moyen Comoe', 'Abengourou', 'Agnibilékrou'),
  ('Agou', 'Adzope', 'Agneby', 'Agboville', 'Agou'),
  ('Akoupe', 'Adzope', 'Agneby', 'Agboville', 'Akoupé'),
  ('Alepe', 'Alepe', 'Lagunes', 'Abidjan', 'Alépé'),
  ('Ando-Kekrenou', 'Beoumi', 'Vallee Du Bandama', 'Bouake', null),
  ('Angoda', 'Toumodi', 'Lacs', 'Yamoussoukro', null),
  ('Anoumaba', 'Bongouanou', 'N''zi Comoe', 'Dimbokro', 'Anoumaba'),
  ('Anyama', 'Abidjan', 'Lagunes', 'Abidjan', 'Anyama'),
  ('Arrah', 'Bongouanou', 'N''zi Comoe', 'Dimbokro', 'Arrah'),
  ('Assikoi', 'Adzope', 'Agneby', 'Agboville', null),
  ('Assinie-Mafia', 'Adiake', 'Sud-Comoe', 'Aboisso', null),
  ('Assuefry', 'Tanda', 'Zanzan', 'Bondoukou', 'Assuefry'),
  ('Attiegouakro', 'Yamoussoukro', 'Lacs', 'Yamoussoukro', null),
  ('Ayame', 'Aboisso', 'Sud-Comoe', 'Aboisso', 'Ayamé'),
  ('Azaguie', 'Agboville', 'Agneby', 'Agboville', 'Azaguié'),
  ('Bagohouo', 'Duekoue', 'Moyen Cavally', 'Guiglo', null),
  ('Bako', 'Odienne', 'Denguele', 'Odienne', 'Bako'),
  ('Bakoubly', 'Toulepleu', 'Moyen Cavally', 'Guiglo', null),
  ('Bangolo', 'Bangolo', 'Montagnes', 'Man', 'Bangolo'),
  ('Banguera', 'M''bahiakro', 'N''zi Comoe', 'Dimbokro', 'Banguera'),
  ('Bassawa', 'Dabakala', 'Vallee Du Bandama', 'Bouake', 'Bassawa'),
  ('Bayota', 'Gagnoa', 'Fromager', 'Gagnoa', null),
  ('Bazre', 'Sinfra', 'Marahoue', 'Bouafle', null),
  ('Becedi-Brignan', 'Adzope', 'Agneby', 'Agboville', null),
  ('Bediala', 'Daloa', 'Haut-Sassandra', 'Daloa', 'Bediala'),
  ('Beoumi', 'Beoumi', 'Vallee Du Bandama', 'Bouake', 'Beoumi'),
  ('Bettie', 'Abengourou', 'Moyen Comoe', 'Abengourou', 'Bettié'),
  ('Biankouma', 'Biankouma', 'Montagnes', 'Man', 'Biankouma'),
  ('Bianouan', 'Aboisso', 'Sud-Comoe', 'Aboisso', null),
  ('Bin-Houye', 'Danane', 'Montagnes', 'Man', 'Bin-Houyé'),
  ('Bingervile', 'Abidjan', 'Lagunes', 'Abidjan', 'Bingerville'),
  ('Blolequin', 'Guiglo', 'Moyen Cavally', 'Guiglo', 'Bloléquin'),
  ('Bocanda', 'Bocanda', 'N''zi Comoe', 'Dimbokro', 'Bocanda'),
  ('Bodokro', 'Beoumi', 'Vallee Du Bandama', 'Bouake', 'Bodokro'),
  ('Boguedia', 'Issia', 'Haut-Sassandra', 'Daloa', null),
  ('Bondoukou', 'Bondoukou', 'Zanzan', 'Bondoukou', 'Bondoukou'),
  ('Bongouanou', 'Bongouanou', 'N''zi Comoe', 'Dimbokro', 'Bongouanou'),
  ('Bonieredougou', 'Dabakala', 'Vallee Du Bandama', 'Bouake', 'Bonieredougou'),
  ('Bonon', 'Bouafle', 'Marahoue', 'Bouafle', 'Bonon'),
  ('Bonoua', 'Grand-Bassam', 'Sud-Comoe', 'Aboisso', 'Bonoua'),
  ('Booko', 'Touba', 'Baffing', 'Touba', 'Booko'),
  ('Borotou', 'Touba', 'Baffing', 'Touba', 'Borotou'),
  ('Botro', 'Bouake', 'Vallee Du Bandama', 'Bouake', 'Botro'),
  ('Bouafle', 'Bouafle', 'Marahoue', 'Bouafle', 'Bouaflé'),
  ('Bouake', 'Bouake', 'Vallee Du Bandama', 'Bouake', 'Bouaké'),
  ('Bouna', 'Bouna', 'Zanzan', 'Bondoukou', 'Bouna'),
  ('Boundiali', 'Boundiali', 'Savanes', 'Korhogo', 'Boundiali'),
  ('Brobo', 'Bouake', 'Vallee Du Bandama', 'Bouake', 'Brobo'),
  ('Buyo', 'Soubre', 'Bas-Sassandra', 'San-Pedro', 'Buyo'),
  ('Cechi', 'Agboville', 'Agneby', 'Agboville', null),
  ('Dabakala', 'Dabakala', 'Vallee Du Bandama', 'Bouake', 'Dabakala'),
  ('Dabou', 'Dabou', 'Lagunes', 'Abidjan', 'Dabou'),
  ('Daloa', 'Daloa', 'Haut-Sassandra', 'Daloa', 'Daloa'),
  ('Danane', 'Danane', 'Montagnes', 'Man', 'Danané'),
  ('Dania', 'Vavoua', 'Haut-Sassandra', 'Daloa', null),
  ('Daoukro', 'Daoukro', 'N''zi Comoe', 'Dimbokro', 'Daoukro'),
  ('Diabo', 'Bouake', 'Vallee Du Bandama', 'Bouake', 'Diabo'),
  ('Dianra', 'Mankono', 'Worodougou', 'Seguela', 'Dianra'),
  ('Diawala', 'Ferkessedougou', 'Savanes', 'Korhogo', 'Diawala'),
  ('Didievi', 'Yamoussoukro', 'Lacs', 'Yamoussoukro', 'Didiévi'),
  ('Diegonefla', 'Oume', 'Fromager', 'Gagnoa', 'Diégonéfla'),
  ('Dieouzon', 'Bangolo', 'Montagnes', 'Man', null),
  ('Dikodougou', 'Boundiali', 'Savanes', 'Korhogo', 'Dikodougou'),
  ('Dimbokro', 'Dimbokro', 'N''zi Comoe', 'Dimbokro', 'Dimbokro'),
  ('Dioulatiedougou', 'Odienne', 'Denguele', 'Odienne', 'Dioulatiédougou'),
  ('Divo', 'Divo', 'Sud-Bandama', 'Divo', 'Divo'),
  ('Djebonoua', 'Bouake', 'Vallee Du Bandama', 'Bouake', 'Djebonoua'),
  ('Djekanou', 'Toumodi', 'Lacs', 'Yamoussoukro', 'Djékanou'),
  ('Djibrosso', 'Seguela', 'Worodougou', 'Seguela', 'Djibrosso'),
  ('Doropo', 'Bouna', 'Zanzan', 'Bondoukou', 'Doropo'),
  ('Dualla', 'Seguela', 'Worodougou', 'Seguela', 'Dualla'),
  ('Duekoue', 'Duekoue', 'Moyen Cavally', 'Guiglo', 'Duékoué'),
  ('Ettrokro', 'Daoukro', 'N''zi Comoe', 'Dimbokro', 'Ettrokro'),
  ('Etueboue', 'Adiake', 'Sud-Comoe', 'Aboisso', 'Etuéboué'),
  ('Facobly', 'Man', 'Montagnes', 'Man', 'Facobly'),
  ('Ferkessedougou', 'Ferkessedougou', 'Savanes', 'Korhogo', 'Ferkessedougou'),
  ('Foumbolo', 'Dabakala', 'Vallee Du Bandama', 'Bouake', 'Foumbolo'),
  ('Foungbesso', 'Touba', 'Baffing', 'Touba', null),
  ('Fresco', 'Divo', 'Sud-Bandama', 'Divo', 'Fresco'),
  ('Fronan', 'Katiola', 'Vallee Du Bandama', 'Bouake', 'Fronan'),
  ('Gadouan', 'Daloa', 'Haut-Sassandra', 'Daloa', null),
  ('Gagnoa', 'Gagnoa', 'Fromager', 'Gagnoa', 'Gagnoa'),
  ('Gbapleu', 'Duekoue', 'Moyen Cavally', 'Guiglo', null),
  ('Gbeleban', 'Odienne', 'Denguele', 'Odienne', null),
  ('Gboguhe', 'Daloa', 'Haut-Sassandra', 'Daloa', 'Gboguhé'),
  ('Gbon', 'Boundiali', 'Savanes', 'Korhogo', 'Gbon'),
  ('Gbonne', 'Biankouma', 'Montagnes', 'Man', 'Gbonné'),
  ('Gnagbodougnoa', 'Gagnoa', 'Fromager', 'Gagnoa', null),
  ('Gohitafla', 'Zuenoula', 'Marahoue', 'Bouafle', 'Gohitafla'),
  ('Goulia', 'Odienne', 'Denguele', 'Odienne', 'Goulia'),
  ('Goumere', 'Bondoukou', 'Zanzan', 'Bondoukou', null),
  ('Grabo', 'Tabou', 'Bas-Sassandra', 'San-Pedro', 'Grabo'),
  ('Grand Morie', 'Agboville', 'Agneby', 'Agboville', null),
  ('Grand-Bassam', 'Grand-Bassam', 'Sud-Comoe', 'Aboisso', 'Grand-Bassam'),
  ('Grand-Bereby', 'San-Pedro', 'Bas-Sassandra', 'San-Pedro', 'Grand-Béréby'),
  ('Grand-Lahou', 'Grand-Lahou', 'Lagunes', 'Abidjan', 'Grand-Lahou'),
  ('Grand-Zattry', 'Soubre', 'Bas-Sassandra', 'San-Pedro', 'Grand-Zattry'),
  ('Guehiebly', 'Duekoue', 'Moyen Cavally', 'Guiglo', null),
  ('Gueyo', 'Sassandra', 'Bas-Sassandra', 'San-Pedro', null),
  ('Guezon', 'Duekoue', 'Moyen Cavally', 'Guiglo', null),
  ('Guiberoua', 'Gagnoa', 'Fromager', 'Gagnoa', 'Guibéroua'),
  ('Guiembe', 'Boundiali', 'Savanes', 'Korhogo', 'Guiembé'),
  ('Guiglo', 'Guiglo', 'Moyen Cavally', 'Guiglo', 'Guiglo'),
  ('Guinteguela', 'Touba', 'Baffing', 'Touba', 'Guintéguéla'),
  ('Guitry', 'Divo', 'Sud-Bandama', 'Divo', 'Guitry'),
  ('Hire', 'Divo', 'Sud-Bandama', 'Divo', 'Hiré'),
  ('Iboguhe', 'Issia', 'Haut-Sassandra', 'Daloa', null),
  ('Issia', 'Issia', 'Haut-Sassandra', 'Daloa', 'Issia'),
  ('Jacqueville', 'Jacqueville', 'Lagunes', 'Abidjan', 'Jacqueville'),
  ('Kanakono', 'Tengrela', 'Savanes', 'Korhogo', 'Kanakono'),
  ('Kani', 'Seguela', 'Worodougou', 'Seguela', 'Kani'),
  ('Kaniasso', 'Odienne', 'Denguele', 'Odienne', 'Kaniasso'),
  ('Karakoro', 'Boundiali', 'Savanes', 'Korhogo', 'Karakoro'),
  ('Kassere', 'Boundiali', 'Savanes', 'Korhogo', 'Kasséré'),
  ('Katiola', 'Katiola', 'Vallee Du Bandama', 'Bouake', 'Katiola'),
  ('Koffi-Amonkro', 'M''bahiakro', 'N''zi Comoe', 'Dimbokro', 'Koffi-Amonkro'),
  ('Kokoumbo', 'Toumodi', 'Lacs', 'Yamoussoukro', 'Kokoumbo'),
  ('Kolia', 'Boundiali', 'Savanes', 'Korhogo', 'Kolia'),
  ('Komborodougou', 'Boundiali', 'Savanes', 'Korhogo', 'Komborodougou'),
  ('Kondrobo', 'Beoumi', 'Vallee Du Bandama', 'Bouake', null),
  ('Konefla', 'Sinfra', 'Marahoue', 'Bouafle', null),
  ('Kong', 'Ferkessedougou', 'Savanes', 'Korhogo', 'Kong'),
  ('Kongasso', 'Mankono', 'Worodougou', 'Seguela', 'Kongasso'),
  ('Koonan', 'Touba', 'Baffing', 'Touba', 'Koonan'),
  ('Korhogo', 'Boundiali', 'Savanes', 'Korhogo', 'Korhogo'),
  ('Koro', 'Touba', 'Baffing', 'Touba', 'Koro'),
  ('Kouassi-Datekro', 'Tanda', 'Zanzan', 'Bondoukou', 'Kouassi-Datekro'),
  ('Kouassi-Kouassikro', 'Daoukro', 'N''zi Comoe', 'Dimbokro', 'Kouassi-Kouassikro'),
  ('Kouetinfla', 'Sinfra', 'Marahoue', 'Bouafle', null),
  ('Kouibly', 'Man', 'Montagnes', 'Man', 'Kouibly'),
  ('Koumbala', 'Ferkessedougou', 'Savanes', 'Korhogo', 'Koumbala'),
  ('Kounahiri', 'Mankono', 'Worodougou', 'Seguela', 'Kounahiri'),
  ('Kouto', 'Boundiali', 'Savanes', 'Korhogo', 'Kouto'),
  ('Kpouebo', 'Toumodi', 'Lacs', 'Yamoussoukro', null),
  ('Lakota', 'Lakota', 'Sud-Bandama', 'Divo', 'Lakota'),
  ('Languibonou', 'Bouake', 'Vallee Du Bandama', 'Bouake', null),
  ('Logouale', 'Man', 'Montagnes', 'Man', 'Logoualé'),
  ('M''bahiakro', 'M''bahiakro', 'N''zi Comoe', 'Dimbokro', 'M''bahiakro'),
  ('M''batto', 'Bongouanou', 'N''zi Comoe', 'Dimbokro', 'M''batto'),
  ('M''bengue', 'Boundiali', 'Savanes', 'Korhogo', 'M''bengué'),
  ('Madinani', 'Odienne', 'Denguele', 'Odienne', 'Madinani'),
  ('Mafere', 'Aboisso', 'Sud-Comoe', 'Aboisso', 'Maféré'),
  ('Mahapleu', 'Danane', 'Montagnes', 'Man', null),
  ('Man', 'Man', 'Montagnes', 'Man', 'Man'),
  ('Mankono', 'Mankono', 'Worodougou', 'Seguela', 'Mankono'),
  ('Marandallah', 'Mankono', 'Worodougou', 'Seguela', 'Marandallah'),
  ('Massala', 'Seguela', 'Worodougou', 'Seguela', 'Massala'),
  ('Meagui', 'Soubre', 'Bas-Sassandra', 'San-Pedro', 'Méagui'),
  ('Minignan', 'Odienne', 'Denguele', 'Odienne', 'Minignan'),
  ('Morondo', 'Seguela', 'Worodougou', 'Seguela', 'Morondo'),
  ('Napieledougou', 'Boundiali', 'Savanes', 'Korhogo', 'Napiélédougou'),
  ('Nassian', 'Bouna', 'Zanzan', 'Bondoukou', 'Nassian'),
  ('Niable', 'Abengourou', 'Moyen Comoe', 'Abengourou', 'Niablé'),
  ('Niadrou', 'Man', 'Montagnes', 'Man', null),
  ('Niakaramandougou', 'Katiola', 'Vallee Du Bandama', 'Bouake', 'Niakaramandougou'),
  ('Niambezaria', 'Lakota', 'Sud-Bandama', 'Divo', null),
  ('Nielle', 'Ferkessedougou', 'Savanes', 'Korhogo', 'Niellé'),
  ('Niofoin', 'Boundiali', 'Savanes', 'Korhogo', 'Niofoin'),
  ('Odienne', 'Odienne', 'Denguele', 'Odienne', 'Odienné'),
  ('Oghwyapo', 'Alepe', 'Lagunes', 'Abidjan', null),
  ('Okrouyo', 'Soubre', 'Bas-Sassandra', 'San-Pedro', null),
  ('Oress-Krobou', 'Agboville', 'Agneby', 'Agboville', null),
  ('Ouangolodougou', 'Ferkessedougou', 'Savanes', 'Korhogo', 'Ouangolodougou'),
  ('Ouaninou', 'Touba', 'Baffing', 'Touba', 'Ouaninou'),
  ('Ouelle', 'Daoukro', 'N''zi Comoe', 'Dimbokro', 'Ouellé'),
  ('Oume', 'Oume', 'Fromager', 'Gagnoa', 'Oumé'),
  ('Ouragahio', 'Gagnoa', 'Fromager', 'Gagnoa', 'Ouragahio'),
  ('Pehe', 'Toulepleu', 'Moyen Cavally', 'Guiglo', null),
  ('Prikro', 'M''bahiakro', 'N''zi Comoe', 'Dimbokro', 'Prikro'),
  ('Rubino', 'Agboville', 'Agneby', 'Agboville', 'Rubino'),
  ('Sago', 'Sassandra', 'Bas-Sassandra', 'San-Pedro', null),
  ('Saïoua', 'Issia', 'Haut-Sassandra', 'Daloa', 'Saïoua'),
  ('Sakassou', 'Sakassou', 'Vallee Du Bandama', 'Bouake', 'Sakassou'),
  ('Samatiguila', 'Odienne', 'Denguele', 'Odienne', 'Samatiguila'),
  ('San-Pedro', 'San-Pedro', 'Bas-Sassandra', 'San-Pedro', 'San-Pédro'),
  ('Sandegue', 'Bondoukou', 'Zanzan', 'Bondoukou', 'Sandégué'),
  ('Sangouine', 'Man', 'Montagnes', 'Man', 'Sangouiné'),
  ('Sapli', 'Bondoukou', 'Zanzan', 'Bondoukou', null),
  ('Sarhala', 'Mankono', 'Worodougou', 'Seguela', 'Sarhala'),
  ('Sassandra', 'Sassandra', 'Bas-Sassandra', 'San-Pedro', 'Sassandra'),
  ('Satama-Sokoro', 'Dabakala', 'Vallee Du Bandama', 'Bouake', 'Satama-Sokoro'),
  ('Satama-Sokouro', 'Dabakala', 'Vallee Du Bandama', 'Bouake', 'Satama-Sokouro'),
  ('Seguela', 'Seguela', 'Worodougou', 'Seguela', 'Seguela'),
  ('Seguelon', 'Odienne', 'Denguele', 'Odienne', 'Séguélon'),
  ('Seitifla', 'Vavoua', 'Haut-Sassandra', 'Daloa', null),
  ('Semien', 'Man', 'Montagnes', 'Man', null),
  ('Seydougou', 'Odienne', 'Denguele', 'Odienne', 'Seydougou'),
  ('Sifie', 'Seguela', 'Worodougou', 'Seguela', 'Sifié'),
  ('Sikensi', 'Dabou', 'Lagunes', 'Abidjan', 'Sikensi'),
  ('Sinematiali', 'Boundiali', 'Savanes', 'Korhogo', 'Sinematiali'),
  ('Sinfra', 'Sinfra', 'Marahoue', 'Bouafle', 'Sinfra'),
  ('Sipilou', 'Biankouma', 'Montagnes', 'Man', 'Sipilou'),
  ('Sirasso', 'Boundiali', 'Savanes', 'Korhogo', 'Sirasso'),
  ('Songon', 'Abidjan', 'Lagunes', 'Abidjan', 'Songon'),
  ('Sorobango', 'Bondoukou', 'Zanzan', 'Bondoukou', null),
  ('Soubre', 'Soubre', 'Bas-Sassandra', 'San-Pedro', 'Soubré'),
  ('Taabo', 'Tiassale', 'Lagunes', 'Abidjan', 'Taabo'),
  ('Tabagne', 'Bondoukou', 'Zanzan', 'Bondoukou', null),
  ('Tabou', 'Tabou', 'Bas-Sassandra', 'San-Pedro', 'Tabou'),
  ('Tafire', 'Katiola', 'Vallee Du Bandama', 'Bouake', 'Tafiré'),
  ('Taï', 'Guiglo', 'Moyen Cavally', 'Guiglo', 'Taï'),
  ('Tanda', 'Tanda', 'Zanzan', 'Bondoukou', 'Tanda'),
  ('Tankesse', 'Tanda', 'Zanzan', 'Bondoukou', null),
  ('Taoudi', 'Bondoukou', 'Zanzan', 'Bondoukou', null),
  ('Tehini', 'Bouna', 'Zanzan', 'Bondoukou', 'Tehini'),
  ('Tengrela', 'Tengrela', 'Savanes', 'Korhogo', 'Tengréla'),
  ('Tiapoum', 'Aboisso', 'Sud-Comoe', 'Aboisso', 'Tiapoum'),
  ('Tiassale', 'Tiassale', 'Lagunes', 'Abidjan', 'Tiassalé'),
  ('Tie-N''diekro', 'Tiebissou', 'Lacs', 'Yamoussoukro', 'Tié-N''diekro'),
  ('Tiebissou', 'Tiebissou', 'Lacs', 'Yamoussoukro', 'Tiébissou'),
  ('Tieme', 'Odienne', 'Denguele', 'Odienne', 'Tiémé'),
  ('Tiemelekro', 'Bongouanou', 'N''zi Comoe', 'Dimbokro', 'Tiemelékro'),
  ('Tieningboue', 'Mankono', 'Worodougou', 'Seguela', 'Tieningboue'),
  ('Tienko', 'Odienne', 'Denguele', 'Odienne', 'Tienko'),
  ('Timbe', 'Katiola', 'Vallee Du Bandama', 'Bouake', null),
  ('Tiobly', 'Toulepleu', 'Moyen Cavally', 'Guiglo', null),
  ('Tioroniaradougou', 'Boundiali', 'Savanes', 'Korhogo', 'Tioroniaradougou'),
  ('Tomoudi-Sakassou', 'Sakassou', 'Vallee Du Bandama', 'Bouake', null),
  ('Tortiya', 'Katiola', 'Vallee Du Bandama', 'Bouake', 'Tortiya'),
  ('Totrodrou', 'Man', 'Montagnes', 'Man', null),
  ('Touba', 'Touba', 'Baffing', 'Touba', 'Touba'),
  ('Toulepleu', 'Toulepleu', 'Moyen Cavally', 'Guiglo', 'Toulepleu'),
  ('Toumodi', 'Toumodi', 'Lacs', 'Yamoussoukro', 'Toumodi'),
  ('Transua', 'Tanda', 'Zanzan', 'Bondoukou', 'Transua'),
  ('Vavoua', 'Vavoua', 'Haut-Sassandra', 'Daloa', 'Vavoua'),
  ('Worofla', 'Seguela', 'Worodougou', 'Seguela', 'Worofla'),
  ('Yakasse-Attobrou', 'Adzope', 'Agneby', 'Agboville', 'Yakassé-Attobrou'),
  ('Yamoussoukro', 'Yamoussoukro', 'Lacs', 'Yamoussoukro', 'Yamoussoukro'),
  ('Yocoboue', 'Divo', 'Sud-Bandama', 'Divo', null),
  ('Zaïbo', 'Daloa', 'Haut-Sassandra', 'Daloa', null),
  ('Zeo', 'Bangolo', 'Montagnes', 'Man', null),
  ('Zikisso', 'Lakota', 'Sud-Bandama', 'Divo', 'Zikisso'),
  ('Zou', 'Bangolo', 'Montagnes', 'Man', null),
  ('Zouan-Hounien', 'Danane', 'Montagnes', 'Man', 'Zouan-Hounien'),
  ('Zoukougbeu', 'Daloa', 'Haut-Sassandra', 'Daloa', 'Zoukougbeu'),
  ('Zuenoula', 'Zuenoula', 'Marahoue', 'Bouafle', 'Zuénoula');
